### ISSUE TITLE
训练自己的数据出现问题

### ISSUE THREAD

**Issue by thinkinds** [njvisionpower/Safety-Helmet-Wearing-Dataset#16]
我参考你的方法搜集图片并标注，建立一个voc格式的数据集，类别也是两类，train_yolo.py里面我也修改了classes，但是训练一开始就报错：
--network mobilenet1.0
use random shape
INFO:root:Namespace(batch_size=8, data_shape=416, dataset='voc', epochs=100, gpus='0', label_smooth=False, log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='60, 80', lr_decay_period=0, lr_mode='step', mixup=False, momentum=0.9, network='mobilenet1.0', no_mixup_epochs=20, no_random_shape=False, no_wd=False, num_samples=5045, num_workers=8, resume='', save_interval=5, save_prefix='yolo3_mobilenet1.0_voc', seed=233, start_epoch=0, syncbn=False, val_interval=1, warmup_epochs=3, warmup_lr=0.0, wd=0.0005)
INFO:root:Start training from [Epoch 0]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/site-packages/gluoncv/data/dataloader.py", line 154, in _worker_fn
    batch = batchify_fn([t_dataset[i] for i in samples])
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/site-packages/gluoncv/data/dataloader.py", line 154, in <listcomp>
    batch = batchify_fn([t_dataset[i] for i in samples])
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/site-packages/mxnet/gluon/data/dataset.py", line 124, in __getitem__
    return self._fn(*item)
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/site-packages/gluoncv/data/transforms/presets/yolo.py", line 160, in __call__
    bbox = tbbox.translate(label, x_offset=expand[0], y_offset=expand[1])
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/site-packages/gluoncv/data/transforms/bbox.py", line 160, in translate
    bbox[:, :2] += (x_offset, y_offset)
IndexError: too many indices for array
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_yolo.py", line 350, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "train_yolo.py", line 261, in train
    for i, batch in enumerate(train_data):
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 451, in __next__
    batch = pickle.loads(ret.get()) if self._dataset is None else ret.get()
  File "/home/zrway/miniconda3/envs/gluon/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: too many indices for array

希望能得到你的帮助，谢谢

**Comment by njvisionpower** [comment]
我遇到过这个问题，可以检查一下数据集中是否包含没有标注bounding box的图像，也就是说有图像和标签但是没有任何标注的box，gluoncv一开始会检查这些。

**Comment by thinkinds** [comment]
检查了一下，每一个xml里面的object下面都有bndbox元素。还有没有其它可能的原因？

njvisionpower <notifications@github.com> 于 2019年11月5日周二 下午3:36写道：

**Comment by njvisionpower** [comment]
参考下这个[链接](https://github.com/dmlc/gluon-cv/issues/401)，检查下标注的label会不会和定义的classes的标签不一致。

**Comment by thinkinds** [comment]
谢谢了，还真是这个问题，找人标注的标签里面有一部分差了个下划线

njvisionpower <notifications@github.com> 于2019年11月5日周二 下午9:48写道：

**Comment by njvisionpower** [comment]
不客气。

**Comment by thinkinds** [comment]
@njvisionpower 又有新问题来麻烦你了。现在模型训练出来了，只能用这种方式加载模型并正常工作：
network = 'yolo3_mobilenet1.0_custom'
net = model_zoo.get_model(network, pretrained=False, classes=classes)

for param in net.collect_params().values():
     if param._data is not None:
         continue
     param.initialize()
 net.reset_class(classes)
 net.collect_params().reset_ctx(ctx)
 net.load_parameters('mobilenet1.0_voc_best.params', ctx=ctx)

我还用export_block导出了模型json和params，
但是如果用下面的语句导入：
net = gluon.SymbolBlock.imports(symbol_file='./occlusion/Occnet-symbol.json',
                                input_names=['data'],
                                param_file='Occnet-0000.params',
                                ctx=ctx)
报错：
mxnet.base.MXNetError: Error in operator _defaultpreprocess0_broadcast_minus0: [16:20:20] c:\jenkins\workspace\mxnet-tag\mxnet\src\operator\tensor\./elemwise_binary_broadcast_op.h:68: Check failed: l == 1 || r == 1: operands could not be broadcast together with shapes [1,3,416,555] [1,1,1,3]

应该怎么处理呢？
