### ISSUE TITLE
模型是否有TensorFlow或者Caffe的版本？

### ISSUE THREAD

**Issue by mengmaren** [njvisionpower/Safety-Helmet-Wearing-Dataset#61]
最近试了您的mxnet的模型，感觉还可以，想在TensorFlow或者Cafee平台下试试，不过自己使用mmdnn转失败，不知道您是否有TensorFlow或Cafee的模型。

mmdnn报错如下：
root@ubuntu:/home/model# python3 -m mmdnn.conversion._script.convertToIR -f mxnet -n darknet53-symbol.json -w darknet53-0000.params -d resnet50 --inputShape 3,112,112

[02:31:24] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.5.0. Attempting to upgrade...
[02:31:24] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
/usr/local/lib/python3.5/dist-packages/mxnet/module/base_module.py:55: UserWarning: You created Module with Module(..., label_names=['softmax_label']) but input with name 'softmax_label' is not found in symbol.list_arguments(). Did you mean one of:
        data
        yolov39_yolooutputv30_offset_0
        yolov39_yolooutputv30_anchor_0
        yolov39_yolooutputv31_offset_1
        yolov39_yolooutputv31_anchor_1
        yolov39_yolooutputv32_offset_2
        yolov39_yolooutputv32_anchor_2
  warnings.warn(msg)
Warning: MXNet Parser has not supported operator null with name data.
Warning: convert the null operator with name [data] into input layer.
Warning: MXNet Parser has not supported operator _arange with name yolov39_yolooutputv30__arange0.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 197, in <module>
    _main()
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 192, in _main
    ret = _convert(args)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/convertToIR.py", line 115, in _convert
    parser.run(args.dstPath)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/common/DataStructure/parser.py", line 22, in run
    self.gen_IR()
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 263, in gen_IR
    self.rename_UNKNOWN(current_node)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/mxnet/mxnet_parser.py", line 374, in rename_UNKNOWN
    raise NotImplementedError()
NotImplementedError

**Comment by SunandShadow** [comment]
mmdnn中好像还没有对mxnet darknet网络的支持吧，我也想将生成的darknet53_voc.params进行转换，主要是想使用在嵌入式中opencv进行模型加载。

**Comment by SunandShadow** [comment]
你参数中使用的是resnet50网络，并非darnet，我个人感觉是这的原因
